// Code generated by "genpls:mock"; DO NOT EDIT.
// github.com/WinPooh32/genpls

package parse

// *MockI1 implements I1.
type MockI1 struct {
	IMethod1Func func ()
	imethod2Func func ()

	Calls struct{
		IMethod1 []struct{ 
			 
		}
		imethod2 []struct{ 
			 
		}
	}
}

func (mock *MockI1) IMethod1() {
	if mock.IMethod1Func == nil {
		panic("nil method IMethod1 is called!")
	}

	callInfo := struct{ 
			
	} {  }

	mock.Calls.IMethod1 = append(mock.Calls.IMethod1, callInfo)

	mock.IMethod1Func()
}

func (mock *MockI1) imethod2() {
	if mock.imethod2Func == nil {
		panic("nil method imethod2 is called!")
	}

	callInfo := struct{ 
			
	} {  }

	mock.Calls.imethod2 = append(mock.Calls.imethod2, callInfo)

	mock.imethod2Func()
}

